"""Add FinancialProfile and AiChatMessage models

Revision ID: 7d97ec4691c6
Revises: 
Create Date: 2026-09-18 00:53:57.641939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d97ec4691c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_ai_chat_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('financial_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_income_pkr', sa.Float(), nullable=True),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('debt_to_income_ratio', sa.Float(), nullable=True),
    sa.Column('savings_rate', sa.Float(), nullable=True),
    sa.Column('financial_stress_level', sa.String(length=20), nullable=True),
    sa.Column('cash_flow_status', sa.String(length=20), nullable=True),
    sa.Column('financial_scenario', sa.String(length=30), nullable=True),
    sa.Column('emergency_fund_pkr', sa.Float(), nullable=True),
    sa.Column('emergency_fund_months', sa.Float(), nullable=True),
    sa.Column('loan_payment_pkr', sa.Float(), nullable=True),
    sa.Column('investment_amount_pkr', sa.Float(), nullable=True),
    sa.Column('subscription_services', sa.Integer(), nullable=True),
    sa.Column('savings_goal_met', sa.Boolean(), nullable=True),
    sa.Column('financial_advice_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_profiles')
    with op.batch_alter_table('ai_chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_chat_user_time')

    op.drop_table('ai_chat_messages')
    # ### end Alembic commands ###
