"""Add groq_api_key and preferred_model to financial_profiles

Revision ID: 893368a6f079
Revises: 7d97ec4691c6
Create Date: 2026-09-18 02:03:43.687230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893368a6f079'
down_revision = '7d97ec4691c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groq_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preferred_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.drop_column('preferred_model')
        batch_op.drop_column('groq_api_key')

    # ### end Alembic commands ###
